apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sec-review-coordinator
  namespace: sec-review
  labels:
    app: sec-review-coordinator
spec:
  selector:
    matchLabels:
      app: sec-review-coordinator
  endpoints:
    - port: "8080"
      path: /metrics
      interval: 15s
