{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sec-review.fullname" . }}-coordinator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sec-review.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    -
      {{- with .host }}
      host: {{ . | quote }}
      {{- end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "sec-review.fullname" $ }}-coordinator
                port:
                  number: {{ $.Values.coordinator.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
