{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sec-review.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sec-review.labels" . | nindent 4 }}
{{- with .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
