import { test, expect, Page } from '@playwright/test'
import { mockApi } from './helpers/mockApi'

/**
 * Verifies the design decision: amber is the single primary accent color across
 * the whole app. Previously, many pages (ExperimentNew, Datasets, CVEDiscovery,
 * Feedback, ExperimentDetail, RunDetail, RunCompare, ToggleChip, etc.) mixed in
 * indigo/violet as their primary, producing a split visual identity. These
 * tests assert that no indigo/violet survives on the rendered pages.
 */

function rgbToKey(r: number, g: number, b: number) {
  return `${r},${g},${b}`
}

async function colorToRgb(page: Page, color: string): Promise<{ r: number; g: number; b: number }> {
  return page.evaluate((c) => {
    const canvas = document.createElement('canvas')
    canvas.width = 1
    canvas.height = 1
    const ctx = canvas.getContext('2d')!
    ctx.fillStyle = c
    ctx.fillRect(0, 0, 1, 1)
    const [r, g, b] = ctx.getImageData(0, 0, 1, 1).data
    return { r, g, b }
  }, color)
}

// Known Tailwind indigo/violet shades we do NOT want on primary surfaces.
// Generated by seeding the browser with the class names so the palette lookup
// is authoritative rather than hard-coded (Tailwind 4 can remap colors).
async function forbiddenPrimaryColors(page: Page): Promise<Set<string>> {
  const classes = [
    'bg-indigo-500', 'bg-indigo-600', 'bg-indigo-700',
    'text-indigo-500', 'text-indigo-600', 'text-indigo-400',
    'bg-violet-500', 'bg-violet-600',
    'text-violet-500', 'text-violet-600',
  ]
  const colors = await page.evaluate(async (cls) => {
    const out: string[] = []
    for (const c of cls) {
      const el = document.createElement('div')
      el.className = c
      document.body.appendChild(el)
      const style = window.getComputedStyle(el)
      out.push(c.startsWith('bg-') ? style.backgroundColor : style.color)
      el.remove()
    }
    return out
  }, classes)

  const forbidden = new Set<string>()
  for (const c of colors) {
    if (!c || c === 'rgba(0, 0, 0, 0)') continue
    const rgb = await colorToRgb(page, c)
    forbidden.add(rgbToKey(rgb.r, rgb.g, rgb.b))
  }
  return forbidden
}

const PAGES = [
  { name: 'experiment-new', path: '/experiments/new' },
  { name: 'datasets', path: '/datasets' },
  { name: 'cve-discovery', path: '/datasets/discover' },
  { name: 'feedback', path: '/feedback' },
]

test.beforeEach(async ({ page }) => {
  await mockApi(page)
})

for (const { name, path } of PAGES) {
  test(`${name}: no buttons use indigo/violet backgrounds`, async ({ page }) => {
    await page.goto(path)
    await page.waitForLoadState('networkidle')

    const forbidden = await forbiddenPrimaryColors(page)

    // Check every visible <button> element's background.
    const buttons = await page.locator('button:visible').all()
    expect(buttons.length).toBeGreaterThan(0)

    const offenders: string[] = []
    for (const btn of buttons) {
      const bgStr = await btn.evaluate((el) => window.getComputedStyle(el).backgroundColor)
      if (!bgStr || bgStr === 'rgba(0, 0, 0, 0)') continue
      const rgb = await colorToRgb(page, bgStr)
      if (forbidden.has(rgbToKey(rgb.r, rgb.g, rgb.b))) {
        const text = (await btn.innerText()).slice(0, 40)
        offenders.push(`"${text}" @ rgb(${rgb.r},${rgb.g},${rgb.b})`)
      }
    }
    expect(
      offenders,
      `Buttons still using indigo/violet on ${path}: ${offenders.join('; ')}`,
    ).toHaveLength(0)
  })
}

test('ToggleChip active state uses amber, not indigo', async ({ page }) => {
  // ExperimentNew has ToggleChips (tool_variant, verification).
  await page.goto('/experiments/new')
  await page.waitForLoadState('networkidle')

  // An "active" chip is the one with the primary fill. In ExperimentNew's
  // Dimensions section, "with_tools" and "without_tools" are both active by
  // default — pick the first active-looking chip.
  const activeChip = page.locator('button, label').filter({ hasText: 'with_tools' }).first()
  await expect(activeChip).toBeVisible()

  // Class list should contain bg-amber-600 (per CHIP_ACTIVE), not bg-indigo-*.
  const classes = await activeChip.getAttribute('class')
  expect(classes ?? '').not.toMatch(/bg-indigo-\d+/)
})
